server:
  port: 10880

spring:
  config:
    import: classpath:application-common.yml

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dbName?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: test
    password:
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource


jwt:
  secret: ""
  expiration: 8640000


system:
  bcos-cfg: "conf/config.toml"
  bcos-group-id: "group0"
  crypto-type: 0
  admin-account: 'admin'
  admin-password: ''
  admin-private-key: ''
  admin-company: '可信第三方'
  contractConfig:
    account-contract: ""
    product-contract: ""
    dataSchema-contract: ""
  fileConfig:
    file-dir: "tmp"

swagger:
  enabled: true


