[cryptoMaterial]

certPath = "conf"                           # The certification path
disableSsl = "false"                        # Communication with nodes without SSL
useSMCrypto = "false"                       # RPC SM crypto type

[network]
defaultGroup="group0"                            # Console default group to connect
peers=["127.0.0.1:20200", "127.0.0.1:20201"]    # The peer list to connect

[account]
#accountFilePath = "accounts/0x7d04603e157d7a272322f89b43ddb78a19dfee93.pem"          # The account file path (default load from the path specified by the keyStoreDir)
# The storage format of account file (Default is "pem", "p12" as an option)

# Default is a randomly generated account
# The randomly generated account is stored in the path specified by the keyStoreDir

# password = ""                 # The password used to load the account file

[threadPool]
# threadPoolSize = "16"         # The size of the thread pool to process message callback
# Default is the number of cpu cores

